### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by oserdiuk** [Nikitskin/WebApiApp#1]
1. DbContext is better to be added like Scoped so that you can inject dbContext into multiple classes and work with the same context in the scope of one user request.
> Transient lifetime services are created **EACH TIME they are requested.** This lifetime works best for lightweight, stateless services.
> Scoped lifetime services are created **once per REQUEST**.
[More here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection
)
2. Remove Web.config file from DbLayer
3. Add navigation properties to all db entities, add EF migrations
4. Remove SaveChanges() method call from the repository. `dbContext.SaveChanges()` should be called in UnitOfWork method SaveChanges() in order to join operations with all tables into one transaction.
5. It would be better to use async methods (e.g. `await dbSet.FindAsync(id)`) if there are any.
6. Simplify repository.GetAll() method. You don't have to enumerate data and add it to a separate list, you can simply return `await dbSet.ToListAsync()`
7. Simplify `repository.Update()` method. You can use ` dbSet.AddOrUpdate(item)` method from `System.Data.Entity.Migrations` namespace or you can retrieve item from db, update fields and change its state (see http://www.entityframeworktutorial.net/EntityFramework4.3/update-entity-using-dbcontext.aspx)
8. Move Services to the separate project for a business logic layer.
9. Create an interface IUnitOfWork, and inject it into constructors of class that uses unitOfWork instance. Register it in DI.
10. Inject DbContext into UnitOfWork constructor so that IoC container is responsible for context lifecycle.

**Comment by Nikitskin** [comment]
Removed services. The rest seems to be according to comments.
Making authorizations and seeds
