### ISSUE TITLE
Project names

### ISSUE THREAD

**Issue by oserdiuk** [Nikitskin/WebApiApp#8]
If solution is called 'TestSolution', then all project in there should be: TestSolution.Web, TestSolution.DbLayer, TestSolution.Dto, TestSolution.ServiceLayer, TestSolution.Logger, TestSolution.Tests

I'm not going to make you rename them, because it's a lot of work without resharper. But you should know that.

**Comment by Nikitskin** [comment]
Fixxed in project_rename branch
